name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: node_modules
          key: v2-dependencies--${{ matrix.node-version }}-${{ runner.OS }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            v2-dependencies--${{ matrix.node-version }}-${{ runner.OS }}-
            v2-dependencies--${{ matrix.node-version }}-

      - name: Install Dependencies
        run: yarn install --prefer-offline --pure-lockfile

      - name: Prettier
        run: yarn run lint:prettier
